
web:
  port: 20080

active: dev

db:
  url: root:123456@tcp(localhost:3306)/admin?charset=utf8mb4&parseTime=True&loc=Local
  debug: true
  autoMigrate: true
  migrateFile: sql/migrate
  # 是否跳过创建外键
  disableForeignKeyConstraintWhenMigrating: true

redis:
  addr: localhost:6379
  password: 123456
  db: 1

authFilter:
  prefix: "perms:"

jwt:
  expire: 86400
  key: ljqlwjerqweroqueroqewr
  bufferTime: 3600
  prefix: "token:"

log:
  level: info
  format: json
  file:

system:
  superManagers:
    - admin
    - yangxs